# doc: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#source-section


package:
  name: adaflow
  # This is the real version, used in releases:
  # version is the last TAG + the number of commits since
  version: 0.0.1
  # version: {{ environ.get('GIT_DESCRIBE_TAG', 'LOCAL').replace("_", ".").replace("Release.","") }}.{{ environ.get('0.0.1', 0) }}
  # version: "0.0.1"
  # This is the version used for the nightlies:
  # nightly version: 2020.09.1b.{{ environ.get('GIT_DESCRIBE_NUMBER', 1) }}

source:
  # path: ../src
  # - url: https://package1.com/a.tar.bz2
  path: .
#  git_url: http://gitlab.alibaba-inc.com/visual-application/xstreamer.git
#  git_rev: master

build:
  number: 1

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux64]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - python
    - setuptools
    - cmake
    - ninja
    - meson
  host:
    - gstreamer 1.22.0
    - gst-plugins-base 1.22.0
    - gst-plugins-good 1.22.0
    - gst-plugins-bad 1.22.0
    - gst-plugins-ugly  1.22.0
    - gst-python  1.22.0
  run: []

about:
  home: ""
  license: Apache License 2.0