name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  cuda-docker-images:
    runs-on: [self-hosted, gpu]
    steps:
      - uses: actions/checkout@v3
      - name: Fetch submodules
        run: git submodule update --init --recursive
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build cuda builder image
        run: docker buildx build --build-arg DEVEL_TAG=latest --push -t adaflow/adaflow-builder-cuda:${RELEASE_VERSION} -f ./docker/adaflow-builder-cuda.dockerfile .
      - name: Build cuda runtime image
        run: docker buildx build --build-arg DEVEL_TAG=${RELEASE_VERSION} --push -t adaflow/adaflow-runtime-cuda:${RELEASE_VERSION} -f ./docker/adaflow-runtime-cuda.dockerfile .

  cpu-only-docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch submodules
        run: git submodule update --init --recursive
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build adaflow-builder-cpu
        run: docker buildx build --build-arg DEVEL_TAG=$(arch)-latest --push -t adaflow/adaflow-builder-cpu:$(arch)-${RELEASE_VERSION} -f ./docker/adaflow-builder-cpu.dockerfile .
      - name: Build adaflow-runtime-cpu
        run: docker buildx build --build-arg DEVEL_TAG=$(arch)-latest --push -t adaflow/adaflow-runtime-cpu:$(arch)-${RELEASE_VERSION} -f ./docker/adaflow-runtime-cpu.dockerfile .

  python-wheel:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Fetch submodules
        run: git submodule update --init --recursive
      - name: Build the Docker image
        run: docker buildx build --build-arg DEVEL_TAG=$(arch)-latest --push -t adaflow/adaflow-builder-cpu:$(arch)-latest -f ./docker/adaflow-builder-cpu.dockerfile .
      - name: Run python build
        run: mkdir -p dist && docker run --rm -v $PWD/dist:/build/adaflow/modules/adaflow-python/dist adaflow/adaflow-builder-cpu:$(arch)-latest-ci cd /build/adaflow/modules/adaflow-python && \
          python -m build .
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

