name: Release

on:
  create:
    tags:
      - "*"

jobs:
  python-wheel:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Fetch submodules
        run: git submodule update --init --recursive
      - name: Build the Docker image
        run: docker buildx build --build-arg DEVEL_TAG=$(arch)-latest --push -t adaflow/adaflow-builder-cpu:$(arch)-latest-ci -f ./docker/adaflow-builder-cpu.dockerfile .
      - name: Run python build
        run: mkdir -p dist && docker run --rm -v $PWD/dist:/build/adaflow/modules/adaflow-python/dist adaflow/adaflow-builder-cpu:$(arch)-latest-ci cd /build/adaflow/modules/adaflow-python && \
          python -m build .
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

